repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.9.1
  hooks:
    - id: ruff
    - id: ruff-format
- repo: https://github.com/fastai/nbdev
  rev: 2.2.10
  hooks:
    - id: nbdev_clean