# Autogenerated by nbdev

d = {
    "settings": {
        "branch": "main",
        "doc_baseurl": "/",
        "doc_host": "https://blog.chickenstats.com",
        "git_url": "https://github.com/chickenandstats/chickenstats-blog",
        "lib_path": "chickenstats_blog",
    },
    "syms": {},
}
