# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/chickenstats-blog',
                'doc_host': 'https://chickenandstats.github.io',
                'git_url': 'https://github.com/chickenandstats/chickenstats-blog',
                'lib_path': 'chickenstats_blog'},
  'syms': {'chickenstats_blog.core': {'chickenstats_blog.core.foo': ('core.html#foo', 'chickenstats_blog/core.py')}}}
