project:
  type: website

format:
  html:
    theme:
      light: light_theme.scss
      dark: dark_theme.scss
    toc: true
    toc-location: right
    keep-md: true
    page-layout: full
  commonmark: default

website:
  title: "chickenstats-blog"
  favicon: images/site/favicon.png
  site-url: https://blog.chickenstats.com
  google-analytics: "G-65XFF92N5R"
  twitter-card: true
  open-graph: true
  navbar:
    background: primary
    search: true
    title: "chickenstats-blog"
    pinned: true
    sticky: true
    collapse-below: md
    left:
      - text: "docs"
        href: https://chickenstats.com/latest/
      - text: "about"
        href: about.ipynb
      - text: "blog"
        href: blog/index.qmd
      - text: "projects"
        href: projects.ipynb
    right:
      - icon: github
        href: "https://github.com/chickenandstats/chickenstats-blog"
  cookie-consent:
    type: express
    style: interstitial
  page-footer:
    left: Copyright &copy; 2025 chicken and stats
    right:
      - icon: github
        href: "https://github.com/chickenandstats/chickenstats-blog"
      - icon: bluesky
        href: "https://bsky.app/profile/chickenandstats.com"

metadata-files: [nbdev.yml, sidebar.yml]

execute:
  freeze: auto