name: Deploy to GitHub Pages

permissions:
  contents: write
  pages: write

on:
  push:
    branches: ["main"]
    paths:
      - "nbs/**"
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GIT_LFS_SKIP_SMUDGE: 1
    steps: [uses: fastai/workflows/quarto-ghp3@master]
